- name: Hello World tag example
  debug:
    msg: "Hello World!"
  tags:
    - hello

- name: Welcome to Ansible Tags tag example
  debug:
    msg: "How are you?"
  tags:
    - welcome

- name: Enjoy tag example
  debug:
    msg: "Enjoy!"
  tags:
    - enjoy

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
  tags:
    - always # always it will run irrespective of tag


- name: Restart Apache Webserver
  service:
    name: apache2
    state: restarted
  tags:
    - restart_apache
    - never  # if you use this it will never run except restart-apache tag



# ansible-playbook -e component=tagss main.yaml --list-tags

# ansible-playbook -e component=tagss main.yaml --tags welcome

# ansible-paybook -e component=tagss main.yaml --skip-tags enjoy

