- name: "import {{component}} app setup mongo.yaml"
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup

- name: "import {{component}} nodejs installtion"
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: "restart {{component}} and reload service"
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd


- name: "{{component}} mongodb configuration"
  ansible.builtin.import_file:
    name: mongodb
    tasks_from: mondodb
