- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup

- name: nodejs install
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs


- name: start and enable cart service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd