- name: vars from prompt
  hosts: web
  vars_prompt: 
  - name: USERNAME
    prompt: "Enter username"
    private: false # visible while typing in prompt
  
  - name: PASSWORD
    prompt: "Enter PASSWORD"
    private: true #invisible while typing

  tasks: 
    - name: "read vars from prompt"
      ansible.builtin.debug: 
        msg: "Hi {{USERNAME}} and PASSWORD is {{PASSWORD}}"